### ISSUE TITLE
Failed to get data. The remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by hdsouza** [junecastillote/MS365HealthReport#10]
We have been using the old code untill 01/04/22.. when the script has been breaking with the error "Invoke-RestMethod : Please use MSGraph to access this resource".
In-order to use the new code, I have installed the new PowerShell Module - MS365HealthReport.
Also we have been using a clientsecret (App setup in Azure)
We modified the Azure app with the specific directions from https://freesoft.dev/program/154244822.
When we run: New-MS365IncidentReport -ClientID $ClientID -ClientSecret $ClientSecret -TenantID $tenantdomain
The error we get is: "Failed to get data. The remote server returned an error: (403) Forbidden."
Keep in mind that the same three variables worked correctly in the old code for authentication.

I also tried with adding the following 2 lines to the start of the code and it fails with the same error:
$TLS12Protocol = [System.Net.SecurityProtocolType] 'Ssl3 , Tls12' 
[System.Net.ServicePointManager]::SecurityProtocol = $TLS12Protocol

**Comment by junecastillote** [comment]
MS had disabled the API that this script uses to retrieve the service health data.

https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-service-communications-api-reference

I am working on a new version (slowly) that would use graph api moving forward. However, I cannot give an ETA yet as I'm working on other projects, too.

**Comment by hdsouza** [comment]
Thanks June for the quick response
